// App Reducer

export const IS_LOGGED_IN = "IS_LOGGED_IN";

// Appointment View
export const FETCH_APPOINTMENTS_LOADING = "FETCH_APPOINTMENTS_LOADING";
export const FETCH_APPOINTMENTS_SUCCESS = "FETCH_APPOINTMENTS_SUCCESS";
export const FETCH_APPOINTMENTS_FAILURE = "FETCH_APPOINTMENTS_FAILURE";

export const MARK_APPOINTMENT_LOADING = "MARK_APPOINTMENT_LOADING";
export const MARK_APPOINTMENT_FAILURE = "MARK_APPOINTMENT_FAILURE";

export const ACCEPT_APPOINTMET_SUCCESS = "ACCEPT_APPOINTMET_SUCCESS";
export const REJECT_APPOINTMET_SUCCESS = "REJECT_APPOINTMET_SUCCESS";
export const REMOVE_REJECTED_APPOINTMENTS = "REMOVE_REJECTED_APPOINTMENTS";
export const RESET_APPOINTMENT_ERROR = "RESET_APPOINTMENT_ERROR";