// App Reducer

export const IS_LOGGED_IN = 'IS_LOGGED_IN';
export const SET_USER_ID = 'SET_USER_ID';

// Seller list View

export const FETCH_SELLERS_LOADING = 'FETCH_SELLERS_LOADING';
export const FETCH_SELLERS_SUCCESS = 'FETCH_SELLERS_SUCCESS';
export const FETCH_SELLERS_FAILURE = 'FETCH_SELLERS_FAILURE';

// Seller search View

export const SEARCH_SELLERS_LOADING = 'SEARCH_SELLERS_LOADING';
export const SEARCH_SELLERS_SUCCESS = 'SEARCH_SELLERS_SUCCESS';
export const SEARCH_SELLERS_FAILURE = 'SEARCH_SELLERS_FAILURE';
